### PR TITLE
Rework clio to be PR based and not issue base

### PR DESCRIPTION
**Pull request by chamons**
https://github.com/chamons/clio/issues/66
https://github.com/chamons/clio/issues/65
https://github.com/chamons/clio/issues/30
https://github.com/chamons/clio/issues/20

When clio was born, the world of macios had not yet embraced well written PRs for every change, and we looked and guessed for things that looked like real bugs.

These days, as everything is a PR, we should just report every PR. We can extend this workflow by being smarter about tags, but this way we don't miss things.

This lets us remove a _lot_ of code and be much simpler under the hood.

I took the chance to split clio into 4 components as I was rewriting things:

- Clio.Utilities - RunCommand, Options, and the error/explain reporting code
- Clio.Ranges - Given git oldest/newest or base/branch calculate a list of commits to consider
- Clio.Requests - Given a list of commits, determine which are PRs and mine useful info for display later. In the future will have some sorting based upon tags.
- Clio - Command line tool that consumes these libraries.

I also took the chance to port it to .net core.

### CODE REVIEW

**Review by VincentDondain — APPROVED** [review]
Code looks good to me but @chamons could you maybe give us examples of the new output?

**Comment by chamons** [comment]
`~/bin/clio/clio --github=xamarin/xamarin-macios --github-pat-file=/Users/donblas/.github-status-pat --base=d16-2 --branch=d16-1 /Users/donblas/Programming/macios/master/xamarin-macios/` for example now gives https://gist.github.com/chamons/b7c1cbbfcc0c88deee97b0e2c0108d6b

**Comment by spouliot** [comment]
nice :) can you retrieve (and print) the PR's labels ? (maybe it's already there and those PR did not have any ?)

**Comment by chamons** [comment]
That's next - https://github.com/chamons/clio/issues/68

**Pull request merged**
